# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, cmdargs, derive, filepath, mtl, parsek, pureMD5
, regexTdfa, split
}:

cabal.mkDerivation (self: {
  pname = "cake";
  version = "1.1.0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    binary cmdargs derive filepath mtl parsek pureMD5 regexTdfa split
  ];
  meta = {
    description = "A build-system library and driver";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
